version: '3.9'
services:
  coffee:
    image: lunch:v3
    build: .
    ports:
    - 80
    environment:
      - TITLE=CoffeBreak
      - COLOR=cyan
  mydb:
    image: mariadb
    volumes:
    - vipdb:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d
    environment:
    - MARIADB_ROOT_PASSWORD=secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080

volumes:
   vipdb: