version: '3.9'
services:
  coffee:
    image: lunch:v3
    build: .
    ports:
    - 80
    environment:
      - TITLE=CoffeBreak
      - COLOR=pink
      - BODY=<iframe src="https://giphy.com/embed/pzryvxGeykOxeC0fWb" width="480" height="400" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/garfield-cat-coffee-pzryvxGeykOxeC0fWb">via GIPHY</a></p>
  mydb:
    #image: mariadb@sha256:dd0f492b6b6e7bb4aa707181b799d4efe42cb3a9f6012ec3dbaf326d402151e8
    image: mariadb:10.11.2
    volumes:
    - vipdb:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d
    environment:
    - MARIADB_ROOT_PASSWORD=secret

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080

volumes:
   vipdb: