version: '3.9'
services:
  coffee:
    image: lunch:v3
    build:
      dockerfile: Dockerfile.alpine
    ports:
    - 80
    environment:
      - VIRTUAL_HOST=coffee.${COMPOSE_PROJECT_NAME}.lvh.me
      - TITLE=${TITLE:-Welcome}
      - COLOR=${COLOR:-lightgreen}
      - BODY=${BODY:-Please use TITLE/COLOR/BODY env vars}
  mydb:
    #image: mariadb@sha256:dd0f492b6b6e7bb4aa707181b799d4efe42cb3a9f6012ec3dbaf326d402151e8
    image: mariadb:10.11.2
    volumes:
    - vipdb:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d
    environment:
    - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-secret}

  adminer:
    image: adminer:4.8.1
    restart: always
    environment:
    - VIRTUAL_HOST=adminer.${COMPOSE_PROJECT_NAME}.lvh.me
    ports:
      - 8080

volumes:
   vipdb:

networks:
  default:
    name: infra_default