version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    restart: always
    command:
      - --retry
      #- --debug
      - --rest
      - --docker.domain=lvh.me
      - --docker.network=infra_default
      - --api.dashboard
      # - --defaultentrypoints=http,https
      # - "--entryPoints=Name:http Address::80"
      # - "--entryPoints=Name:https Address::443 TLS"
      # - --acme.email=example@gmail.com
      # - --acme.storage=/etc/acme/acme.json
      # - --acme.entryPoint=https
      # - --acme.onHostRule=true
      # - --acme.httpchallenge.entrypoint=http
    labels:
      - "traefik.frontend.rule=Host:traefik.lvh.me"
      - "traefik.port=8080"
    ports:
      - 80:80
      # - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - acme:/etc/acme

networks:
  default:
    external:
      name: infra_default

# volumes: 
#   acme: